import esbuild from "esbuild";
import process from "process";
import fs from "fs";
import path from "path";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

/**
 * Three build targets:
 *   plugin   -- the frozen Obsidian plugin (main.js). Unchanged; kept until Phase 5
 *               so the port can be diffed against v2.5.6.
 *   app      -- the standalone Electron app: main + preload + renderer -> dist-app/
 *
 * Usage: node esbuild.config.mjs [plugin|app] [production|watch]
 */
const target = process.argv[2] ?? "plugin";
const mode = process.argv[3] ?? (process.argv[2] === "production" ? "production" : "dev");
const prod = mode === "production" || process.argv[2] === "production";

// ---------------------------------------------------------------- plugin target

const pluginConfig = {
  banner: { js: banner },
  entryPoints: ["main.ts"],
  bundle: true,
  external: [
    "obsidian", "electron",
    "@codemirror/autocomplete", "@codemirror/collab", "@codemirror/commands",
    "@codemirror/language", "@codemirror/lint", "@codemirror/search",
    "@codemirror/state", "@codemirror/view",
    "@lezer/common", "@lezer/highlight", "@lezer/lr",
    "path", "fs", "os", "zlib", "child_process",
  ],
  format: "cjs",
  target: "es2020",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: "main.js",
  minify: false,
};

// ------------------------------------------------------------------- app target

const OUT = "dist-app";

/** Main and preload run in Node/Electron; everything Node-ish stays external. */
const electronProcessConfig = (entry, outfile) => ({
  entryPoints: [entry],
  bundle: true,
  platform: "node",
  format: "cjs",
  target: "node20",
  // Native/optional-native deps stay external: main runs in Node and resolves them
  // from node_modules at runtime (electron-builder ships them). pdfjs-dist's legacy
  // build optionally requires `canvas`, which is a .node binary esbuild cannot bundle.
  external: ["electron", "pdfjs-dist", "canvas"],
  outfile: path.join(OUT, outfile),
  sourcemap: prod ? false : "inline",
  minify: prod,
  logLevel: "info",
});

/**
 * The renderer is sandboxed: no Node, no `require`. Anything that resolves to a
 * Node built-in here is a bug, so we let esbuild fail rather than shim it.
 * `obsidian` resolves to the compatibility shim -- this alias is the single switch
 * that makes the 42 coupled files compile unchanged (Phase 2+).
 */
const rendererConfig = {
  entryPoints: ["src/renderer/main.ts"],
  bundle: true,
  platform: "browser",
  format: "iife",
  target: "es2022",
  outfile: path.join(OUT, "renderer", "renderer.js"),
  sourcemap: prod ? false : "inline",
  minify: prod,
  logLevel: "info",
  alias: {
    // Not yet a full module -- Phase 2 adds src/obsidian-shim/index.ts and this
    // starts resolving real imports. Harmless until then: nothing imports it.
    obsidian: path.resolve("src/obsidian-shim"),
    // THE sandbox switch: the renderer gets the window.host forwarder, never the
    // Node implementation. If this alias is ever dropped, the renderer build fails
    // to resolve child_process/fs rather than silently shipping them.
    "host-impl": path.resolve("src/host/impl.bridge.ts"),
  },
};

function copyRendererStatics() {
  const dest = path.join(OUT, "renderer");
  fs.mkdirSync(dest, { recursive: true });
  for (const file of ["index.html", "renderer.css"]) {
    fs.copyFileSync(path.join("src/renderer", file), path.join(dest, file));
  }
}

// ------------------------------------------------------------------------ run

if (target === "app") {
  copyRendererStatics();
  const configs = [
    electronProcessConfig("electron/main.ts", "main.js"),
    electronProcessConfig("electron/preload.ts", "preload.js"),
    rendererConfig,
  ];

  if (mode === "watch") {
    const contexts = await Promise.all(configs.map((c) => esbuild.context(c)));
    await Promise.all(contexts.map((c) => c.watch()));
  } else {
    await Promise.all(configs.map((c) => esbuild.build(c)));
    console.log(`Built app -> ${OUT}/`);
  }
} else {
  const context = await esbuild.context(pluginConfig);
  if (prod) {
    await context.rebuild();
    process.exit(0);
  } else {
    await context.watch();
  }
}
